### ISSUE TITLE
Error: required value Dashboard must not be empty

### ISSUE THREAD

**Issue by bfal78** [andylamp/grafana-tp-link#2]
Hello,

i try your Script on Debian Linux VM and got an Error at the Grafana Dashboard Import.

```
 -- Setting up Prometheus was successful
 ** Dashboard json was not found - trying to fetch from remote: https://raw.githubusercontent.com/andylamp/grafana-tp-link/master/dash.json
 -- Dashboard json definition was fetched successfully at ./dash.json
 !! Could not register grafana dashboard... something went wrong -- cannot continue
 !! Error while creating and registering the grafana dashboard... cannot continue
 !! Encountered an error while registering Grafana dashboard and/or its data source - cannot continue
```

from the grafana.log i see the Error "required value Dashboard must not be empty".

```
logger=context t=2022-03-19T22:16:45.35+0000 lvl=info msg="Request Completed" method=HEAD path=/api status=401 remote_addr=172.18.0.1 time_ms=0 size=0 referer=
logger=context t=2022-03-19T22:16:45.62+0000 lvl=eror msg="bad request data" error="required value Dashboard must not be empty" remote_addr=172.18.0.1
logger=context t=2022-03-19T22:16:45.62+0000 lvl=info msg="Request Completed" method=POST path=/api/dashboards/db status=400 remote_addr=172.18.0.1 time_ms=10 size=30 referer=
```

Which value could Grafana mean at the dash.json? Maybee you could help me?

Thanks a lot

**Comment by andylamp** [comment]
hi, thanks for flagging this. I was able to reproduce this, it seems that the updated `dash.json` broke some installations, I have reverted to the old one, which should work.

Please try again after fetching and it should work.

**Comment by bfal78** [comment]
Thanks for your extreme fast answer. Now it works without errors and I can play around a bit.

**Comment by andylamp** [comment]
glad to hear @bfal78, enjoy this while you can as I hear HS110 plugs are out of production... the new P110 plugs are quite different and I have to make a new solution for these... in due course.

**Comment by bfal78** [comment]
I have HS110 plugs for test and also kp115 plugs. There exists a Python Libary that could connect (https://github.com/python-kasa/python-kasa). I Play a little bit and will see what works.

**Comment by andylamp** [comment]
Yes, KP115 is more recent; unfortunately, there are rumors that the entire kasa lineup is discontinued in lieu of tapo products. These use different API and thus the solution that am using needs to be reworked to support these...

In any case, happy experimentation!

**Comment by meyerbro** [comment]
Any news about KP115 and P110? Did you guys manage to integrate them?

**Comment by andylamp** [comment]
hey, KP115 should work out of the box, P110 is not supported nor it will be supported in the future -  this script is for kasa based devices, not Tapo ones.
