### ISSUE TITLE
Not Really An Issue - But What Is emeter["power"]?

### ISSUE THREAD

**Issue by whitedavidp** [andylamp/grafana-tp-link#6]
I have an HS110 that still has old firmware and I can monitor it off port 9999. I get the emeter information and understand the following to be the case:

current is amps,
voltage is volts,
total is kwHs.

But what is power? I thought it was watts. But I am not sure at all now as I cannot seem to compute the values I see from the current and voltage I see in the same entry. This would seem to be single phase, 120v, USA utility power. So it would seen this formula would apply:
    P = PF × I × U
where:
    P – Power or wattage;
    PF – Power factor;
    I – Electrical current; and
    U – Voltage.
And I understand that the power factor varies from 0 to 1. One represents the most efficient use of power, while 0 means the opposite. 

However, I cannot seem to get the power result being displayed:
{"emeter":{"get_realtime":{"current":0.020707,"voltage":124.223949,"power":0.371734,"total":1.040000,"err_code":0}}}

Thanks

**Comment by andylamp** [comment]
Hi, thanks! This is a wrapper around https://github.com/fffonion/tplink-plug-exporter, which exports the metrics to prometheus and are displayed in Grafana.

The Power (watts) should be roughly P = I * V, so in your example it would be the value of current times the voltage. Meaning it would be around 2.5W...

Hope this helps.

**Comment by whitedavidp** [comment]
Thanks so much! I agree with your math. So why does the json contain "power":0.371734 ? That is nothing like 2.5 and that is why I am so baffled. Cheers!

**Comment by andylamp** [comment]
no problem, if anything is uncertain please open the issue again!
